name 'example42-rclocal'
version '2.0.2'

author 'Alessandro Franceschi'
license 'Apache2'
project_page 'http://www.example42.com'
source 'https://github.com/example42/puppet-rclocal'
summary 'Puppet module ro manage rc.local'
description 'This module manages rc.local'
dependency 'example42/puppi', '>=2.0.0'
